### ISSUE TITLE
Bug with magma ADT type as output type

### ISSUE THREAD

**Issue by rdaly525** [cdonovick/peak#148] opened 2020-04-06 05:23 UTC
I am trying to get AADT constructors working in peak, but I ran across this annoying bug. The top code is something that works in magma, so I would expect it to work in peak as well. 

```
def test_magma_bug():

    #This works.
    OutT =magma.Tuple[magma.Bit, magma.Bit]
    @magma.circuit.combinational
    def PEGold(in0: magma.Bit) -> OutT:
        return OutT(in0, in0)

    #This does not work
    @family_closure
    def PEbug_fc(family):
        Bit = family.Bit
        OutT = Tuple[Bit, Bit]
        @assemble(family, locals(), globals())
        class PEbug(Peak):
            def __call__(self, in0: Bit) -> OutT:
                return OutT(in0, in0)

        return PETuple

    PE_magma = PEbug_fc(magma.get_family())
```

The error is 
```
Traceback (most recent call last):
  File "/Users/rdaly/magma/magma/ast_utils.py", line 54, in compile_function_to_file
    exec(code, defn_env)
  File ".magma/PEbug_comb.py", line 1, in <module>
    class PEbug_comb(m.Circuit):
  File ".magma/PEbug_comb.py", line 2, in PEbug_comb
    io = m.IO(in0=m.In(Bit), O=m.Out(t))
  File "/Users/rdaly/magma/magma/t.py", line 152, in Out
    return T.qualify(Direction.Out)
AttributeError: 'str' object has no attribute 'qualify'
```
The error is within circuit.combinatioanl parsing the IO, so the adt constructor hasn't even been called yet. 

Debugging this a bit, I realized that the 't' is from https://github.com/cdonovick/peak/blob/c29dad28fc345b7a011a6faee5b57a11977fe144/peak/features.py#L135 and due to circuit.combinational using the environment, somewhere must have set 't' to be a string. I can get further if I rename 't' to some other unused variable.

I am a little unsure exactly why this is all occurring. Any thoughts on how to make compiling circuit.combinational a bit safer?

**Comment by cdonovick** [comment] 2020-04-06 06:12
I wouldn't expect that to work

**Comment by cdonovick** [comment] 2020-04-06 06:19
There is no support for constructing an ADT type in line.  You would need to construct an assembled type for SMT or Magma.  I also don't see what this gets you when you could just return a python tuple and everything would work.

**Comment by rdaly525** [comment] 2020-04-06 06:24
I know that the constructor in the body needs to be an assembled ADT for smt/hwtypes. The purpose of this is a minimal failing test is to show there is something wrong with peak/magma parsing the annotations of the call function. Replace the __call__ body with "assert 0" and you still get the same error.

**Comment by cdonovick** [comment] 2020-04-06 06:25
No nothings wrong with it you are using an unsupported type.

**Comment by rdaly525** [comment] 2020-04-06 16:00
Okay, as a follow up on Caleb and my slack chat, I think the determining factor is that a MagmaADT type as an output type does not quite work yet.

**Comment by rsetaluri** [comment] 2020-04-06 19:12
@rdaly525 @cdonovick, is this related to #146?

**Comment by rdaly525** [comment] 2020-04-06 19:38
@rsetaluri I just tried your branch on that bug with no luck at resolving this issue. Have we confirmed that any magma-protocol type works as an output type in circuit.combinational/sequential?

**Comment by cdonovick** [comment] 2020-04-06 21:02
@rsetaluri https://github.com/phanrahan/magma/issues/671

**Comment by rsetaluri** [comment] 2020-04-06 22:46
See https://github.com/phanrahan/magma/pull/672

**Comment by rdaly525** [comment] 2020-04-06 23:51
I can confirm that if the name aliasing issue is fixed, then @rsetaluri magma PR works. I had to change the 't' in https://github.com/cdonovick/peak/blob/c29dad28fc345b7a011a6faee5b57a11977fe144/peak/features.py#L135 to some other name. Is there any sane way to also fix the name aliasing?

**Comment by rsetaluri** [comment] 2020-04-06 23:57
@rdaly525 not sure what the issue there is, can you elucidate?

**Comment by rdaly525** [comment] 2020-04-07 00:02
When generating the .magma/PEbug_comb.py there is a variable named 't' which represents the output of the output type of the circuit (you can see that in the error message I posted in this issue). The reason that is named 't' is because the variable in features.py code I referenced is named 't'. Within magma/syntax/sequential.py, a variable named 't' is set as a string and that particular variable is used when trying to exec PEbug_comb.py, thus causing the error message in the issue

**Comment by rdaly525** [comment] 2020-04-07 00:04
If I change the variable in features.py to something else (which is not used in sequential.py), I do not get the error.

**Comment by rsetaluri** [comment] 2020-04-07 00:06
so the problem is that the `exec` code path is reserving `t` in the environment for it's own use, though it could be coming from the user code?

**Comment by rsetaluri** [comment] 2020-04-12 18:56
@rdaly525 can we close this for now?

**Comment by rdaly525** [comment] 2020-04-12 23:34
Tracking https://github.com/phanrahan/magma/issues/679

**Comment by rsetaluri** [comment] 2020-04-12 23:42
@rdaly525 thanks. closing this

**Closed by rsetaluri** 2020-04-12 23:42 UTC
